const countries = [
    {
      value: "AF",
      label: "Afghanistan",
      phoneCode: "+93",
      currencyCode: "AFN",
      countryCode: "AF",
      flag: "AF",
    },
    {
      value: "AL",
      label: "Albania",
      phoneCode: "+355",
      currencyCode: "ALL",
      countryCode: "AL",
      flag: "AL",
    },
    {
      value: "DZ",
      label: "Algeria",
      phoneCode: "+213",
      currencyCode: "DZD",
      countryCode: "DZ",
      flag: "DZ",
    },
    {
      value: "AS",
      label: "American Samoa",
      phoneCode: "+1684",
      currencyCode: "USD",
      countryCode: "AS",
      flag: "AS",
    },
    {
      value: "AD",
      label: "Andorra",
      phoneCode: "+376",
      currencyCode: "EUR",
      countryCode: "AD",
      flag: "AD",
    },
    {
      value: "AO",
      label: "Angola",
      phoneCode: "+244",
      currencyCode: "AOA",
      countryCode: "AO",
      flag: "AO",
    },
    {
      value: "AI",
      label: "Anguilla",
      phoneCode: "+1264",
      currencyCode: "XCD",
      countryCode: "AI",
      flag: "AI",
    },
    {
      value: "AG",
      label: "Antigua and Barbuda",
      phoneCode: "+1268",
      currencyCode: "XCD",
      countryCode: "AG",
      flag: "AG",
    },
    {
      value: "AR",
      label: "Argentina",
      phoneCode: "+54",
      currencyCode: "ARS",
      countryCode: "AR",
      flag: "AR",
    },
    {
      value: "AM",
      label: "Armenia",
      phoneCode: "+374 ",
      currencyCode: "AMD",
      countryCode: "AM",
      flag: "AM",
    },
    {
      value: "AW",
      label: "Aruba",
      phoneCode: "+297",
      currencyCode: "AWG",
      countryCode: "AW",
      flag: "AW",
    },
    {
      value: "AU",
      label: "Australia",
      phoneCode: "+61",
      currencyCode: "AUD",
      countryCode: "AU",
      flag: "AU",
    },
    {
      value: "AT",
      label: "Austria",
      phoneCode: "+43",
      currencyCode: "EUR",
      countryCode: "AT",
      flag: "AT",
    },
    {
      value: "AZ",
      label: "Azerbaijan",
      phoneCode: "+994",
      currencyCode: "AZN",
      countryCode: "AZ",
      flag: "AZ",
    },
    {
      value: "BS",
      label: "Bahamas",
      phoneCode: "+1242",
      currencyCode: "BSD",
      countryCode: "BS",
      flag: "BS",
    },
    {
      value: "BH",
      label: "Bahrain",
      phoneCode: "+973",
      currencyCode: "BHD",
      countryCode: "BH",
      flag: "BH",
    },
    {
      value: "BD",
      label: "Bangladesh",
      phoneCode: "+880",
      currencyCode: "BDT",
      countryCode: "BD",
      flag: "BD",
    },
    {
      value: "BB",
      label: "Barbados",
      phoneCode: "+1246",
      currencyCode: "BBD",
      countryCode: "BB",
      flag: "BB",
    },
    {
      value: "BY",
      label: "Belarus",
      phoneCode: "+375",
      currencyCode: "BYN",
      countryCode: "BY",
      flag: "BY",
    },
    {
      value: "BE",
      label: "Belgium",
      phoneCode: "+32",
      currencyCode: "EUR",
      countryCode: "BE",
      flag: "BE",
    },
    {
      value: "BZ",
      label: "Belize",
      phoneCode: "+501",
      currencyCode: "BZD",
      countryCode: "BZ",
      flag: "BZ",
    },
    {
      value: "BJ",
      label: "Benin",
      phoneCode: "+229",
      currencyCode: "XOF",
      countryCode: "BJ",
      flag: "BJ",
    },
    {
      value: "BM",
      label: "Bermuda",
      phoneCode: "+1441",
      currencyCode: "BMD",
      countryCode: "BM",
      flag: "BM",
    },
    {
      value: "BT",
      label: "Bhutan",
      phoneCode: "+975",
      currencyCode: "BTN",
      countryCode: "BT",
      flag: "BT",
    },
    {
      value: "BO",
      label: "Bolivia",
      phoneCode: "+591",
      currencyCode: "BOB",
      countryCode: "BO",
      flag: "BO",
    },
    {
      value: "BQ",
      label: "Bonaire, Sint Eustatius and Saba",
      phoneCode: "+599",
      currencyCode: "USD",
      countryCode: "BQ",
      flag: "BQ",
    },
    {
      value: "BA",
      label: "Bosnia and Herzegovina",
      phoneCode: "+387",
      currencyCode: "BAM",
      countryCode: "BA",
      flag: "BA",
    },
    {
      value: "BW",
      label: "Botswana",
      phoneCode: "+267",
      currencyCode: "BWP",
      countryCode: "BW",
      flag: "BW",
    },
    {
      value: "BV",
      label: "Bouvet Island",
      phoneCode: "+47",
      currencyCode: "NOK",
      countryCode: "BV",
      flag: "BV",
    },
    {
      value: "BR",
      label: "Brazil",
      phoneCode: "+55",
      currencyCode: "BRL",
      countryCode: "BR",
      flag: "BR",
    },
    {
      value: "IO",
      label: "British Indian Ocean Territory",
      phoneCode: "+246",
      currencyCode: "USD",
      countryCode: "IO",
      flag: "IO",
    },
    {
      value: "BN",
      label: "Brunei Darussalam",
      phoneCode: "+673",
      currencyCode: "BND",
      countryCode: "BN",
      
      flag: "BN",
    },
    {
      value: "BG",
      label: "Bulgaria",
      phoneCode: "+359",
      currencyCode: "BGN",
      countryCode: "BG",
      flag: "BG",
    },
    {
      value: "BF",
      label: "Burkina Faso",
      phoneCode: "+226",
      currencyCode: "XOF",
      countryCode: "BF",
      flag: "BF",
    },
    {
      value: "BI",
      label: "Burundi",
      phoneCode: "+257",
      currencyCode: "BIF",
      countryCode: "BI",
      flag: "BI",
    },
    {
      value: "CV",
      label: "Cabo Verde",
      phoneCode: "+238",
      currencyCode: "CVE",
      countryCode: "CV",
      flag: "CV",
    },
    {
      value: "KH",
      label: "Cambodia",
      phoneCode: "+855",
      currencyCode: "KHR",
      countryCode: "KH",
      flag: "KH",
    },
    {
      value: "CM",
      label: "Cameroon",
      phoneCode: "+237",
      currencyCode: "XAF",
      countryCode: "CM",
      flag: "CM",
    },
    {
      value: "CA",
      label: "Canada",
      phoneCode: "+1",
      currencyCode: "CAD",
      countryCode: "CA",
      flag: "CA",
    },
    {
      value: "KY",
      label: "Cayman Islands",
      phoneCode: "+1345",
      currencyCode: "KYD",
      countryCode: "KY",
      flag: "KY",
    },
    {
      value: "CF",
      label: "Central African Republic",
      phoneCode: "+236",
      currencyCode: "XAF",
      countryCode: "CF",
      flag: "CF",
    },
    {
      value: "TD",
      label: "Chad",
      phoneCode: "+235",
      currencyCode: "XAF",
      countryCode: "TD",
      flag: "TD",
    },
    {
      value: "CL",
      label: "Chile",
      phoneCode: "+56",
      currencyCode: "CLP",
      countryCode: "CL",
      flag: "CL",
    },
    {
      value: "CN",
      label: "China",
      phoneCode: "+86",
      currencyCode: "CNY",
      countryCode: "CN",
      flag: "CN",
    },
    {
      value: "CX",
      label: "Christmas Island",
      phoneCode: "+61",
      currencyCode: "AUD",
      countryCode: "CX",
      flag: "CX",
    },
    {
      value: "CC",
      label: "Cocos (Keeling) Islands",
      phoneCode: "+61",
      currencyCode: "AUD",
      countryCode: "CC",
      flag: "CC",
    },
    {
      value: "CO",
      label: "Colombia",
      phoneCode: "+57",
      currencyCode: "COP",
      countryCode: "CO",
      flag: "CO",
    },
    {
      value: "KM",
      label: "Comoros",
      phoneCode: "+269",
      currencyCode: "KMF",
      countryCode: "KM",
      flag: "KM",
    },
    {
      value: "CD",
      label: "Congo, Democratic Republic of the",
      phoneCode: "+243",
      currencyCode: "CDF",
      countryCode: "CD",
      flag: "CD",
    },
    {
      value: "CG",
      label: "Congo, Republic of the",
      phoneCode: "+242",
      currencyCode: "XAF",
      countryCode: "CG",
      flag: "CG",
    },
    {
      value: "CK",
      label: "Cook Islands",
      phoneCode: "+682",
      currencyCode: "NZD",
      countryCode: "CK",
      flag: "CK",
    },
    {
      value: "CR",
      label: "Costa Rica",
      phoneCode: "+506",
      currencyCode: "CRC",
      countryCode: "CR",
      flag: "CR",
    },
    {
      value: "HR",
      label: "Croatia",
      phoneCode: "+385",
      currencyCode: "HRK",
      countryCode: "HR",
      flag: "HR",
    },
    {
      value: "CU",
      label: "Cuba",
      phoneCode: "+53",
      currencyCode: "CUP",
      countryCode: "CU",
      flag: "CU",
    },
    {
      value: "CW",
      label: " Curaçao",
      phoneCode: "+599",
      currencyCode: "ANG",
      countryCode: "CW",
      flag: "CW",
    },
    {
      value: "CY",
      label: "Cyprus",
      phoneCode: "+357",
      currencyCode: "EUR",
      countryCode: "CY",
      flag: "CY",
    },
    {
      value: "CZ",
      label: "Czech Republic",
      phoneCode: "+420",
      currencyCode: "CZK",
      countryCode: "CZ",
      flag: "CZ",
    },
    {
      value: "DK",
      label: "Denmark",
      phoneCode: "+45",
      currencyCode: "DKK",
      countryCode: "DK",
      flag: "DK",
    },
    {
      value: "DJ",
      label: "Djibouti",
      phoneCode: "+253",
      currencyCode: "DJF",
      countryCode: "DJ",
      flag: "DJ",
    },
    {
      value: "DM",
      label: "Dominica",
      phoneCode: "+1767",
      currencyCode: "XCD",
      countryCode: "DM",
      flag: "DM",
    },
    {
      value: "DO",
      label: "Dominican Republic",
      phoneCode: "+1",
      currencyCode: "DOP",
      countryCode: "DO",
      flag: "DO",
    },
    {
      value: "EC",
      label: "Ecuador",
      phoneCode: "+593",
      currencyCode: "USD",
      countryCode: "EC",
      flag: "EC",
    },
    {
      value: "EG",
      label: "Egypt",
      phoneCode: "+20",
      currencyCode: "EGP",
      countryCode: "EG",
      flag: "EG",
    },
    {
      value: "SV",
      label: "El Salvador",
      phoneCode: "+503",
      currencyCode: "USD",
      countryCode: "SV",
      flag: "SV",
    },
    {
      value: "GQ",
      label: "Equatorial Guinea",
      phoneCode: "+240",
      currencyCode: "XAF",
      countryCode: "GQ",
      flag: "GQ",
    },
    {
      value: "ER",
      label: "Eritrea",
      phoneCode: "+291",
      currencyCode: "ERN",
      countryCode: "ER",
      flag: "ER",
    },
    {
      value: "EE",
      label: "Estonia",
      phoneCode: "+372",
      currencyCode: "EUR",
      countryCode: "EE",
      flag: "EE",
    },
    {
      value: "SZ",
      label: "Eswatini",
      phoneCode: "+268",
      currencyCode: "SZL",
      countryCode: "SZ",
      flag: "SZ",
    },
    {
      value: "ET",
      label: "Ethiopia",
      phoneCode: "+251",
      currencyCode: "ETB",
      countryCode: "ET",
      flag: "ET",
    },
    {
      value: "FK",
      label: "Falkland Islands (Malvinas)",
      phoneCode: "+500",
      currencyCode: "FKP",
      countryCode: "FK",
      flag: "FK",
    },
    {
      value: "FO",
      label: "Faroe Islands",
      phoneCode: "+298",
      currencyCode: "DKK",
      countryCode: "FO",
      flag: "FO",
    },
    {
      value: "FJ",
      label: "Fiji",
      phoneCode: "+679",
      currencyCode: "FJD",
      countryCode: "FJ",
      flag: "FJ",
    },
    {
      value: "FI",
      label: "Finland",
      phoneCode: "+358",
      currencyCode: "EUR",
      countryCode: "FI",
      flag: "FI",
    },
    {
      value: "FR",
      label: "France",
      phoneCode: "+33",
      currencyCode: "EUR",
      countryCode: "FR",
      flag: "FR",
    },
    {
      value: "GF",
      label: "French Guiana",
      phoneCode: "+594",
      currencyCode: "EUR",
      countryCode: "GF",
      flag: "GF",
    },
    {
      value: "PF",
      label: "French Polynesia",
      phoneCode: "+689",
      currencyCode: "XPF",
      countryCode: "PF",
      flag: "PF",
    },
    {
      value: "GA",
      label: "Gabon",
      phoneCode: "+241",
      currencyCode: "XAF",
      countryCode 
  : "GA",
      flag: "GA",
    },
    {
      value: "GM",
      label: "Gambia",
      phoneCode: "+220",
      currencyCode: "GMD",
      countryCode: "GM",
      flag: "GM",
    },
    {
      value: "GE",
      label: "Georgia",
      phoneCode: "+995",
      currencyCode: "GEL",
      countryCode: "GE",
      flag: "GE",
    },
    {
      value: "DE",
      label: "Germany",
      phoneCode: "+49",
      currencyCode: "EUR",
      countryCode: "DE",
      flag: "DE",
    },
    {
      value: "GH",
      label: "Ghana",
      phoneCode: "+233",
      currencyCode: "GHS",
      countryCode: "GH",
      flag: "GH",
    },
    {
      value: "GI",
      label: "Gibraltar",
      phoneCode: "+350",
      currencyCode: "GIP",
      countryCode: "GI",
      flag: "GI",
    },
    {
      value: "GR",
      label: "Greece",
      phoneCode: "+30",
      currencyCode: "EUR",
      countryCode: "GR",
      flag: "GR",
    },
    {
      value: "GL",
      label: "Greenland",
      phoneCode: "+299",
      currencyCode: "DKK",
      countryCode: "GL",
      flag: "GL",
    },
    {
      value: "GD",
      label: "Grenada",
      phoneCode: "+1473",
      currencyCode: "XCD",
      countryCode: "GD",
      flag: "GD",
    },
    {
      value: "GP",
      label: "Guadeloupe",
      phoneCode: "+590",
      currencyCode: "EUR",
      countryCode: "GP",
      flag: "GP",
    },
    {
      value: "GU",
      label: "Guam",
      phoneCode: "+1671",
      currencyCode: "USD",
      countryCode: "GU",
      flag: "GU",
    },
    {
      value: "GT",
      label: "Guatemala",
      phoneCode: "+502",
      currencyCode: "GTQ",
      countryCode: "GT",
      flag: "GT",
    },
    {
      value: "GG",
      label: "Guernsey",
      phoneCode: "+44",
      currencyCode: "GBP",
      countryCode: "GG",
      flag: "GG",
    },
    {
      value: "GN",
      label: "Guinea",
      phoneCode: "+224",
      currencyCode: "GNF",
      countryCode: "GN",
      flag: "GN",
    },
    {
      value: "GW",
      label: "Guinea-Bissau",
      phoneCode: "+245",
      currencyCode: "XOF",
      countryCode: "GW",
      flag: "GW",
    },
    {
      value: "GY",
      label: "Guyana",
      phoneCode: "+592",
      currencyCode: "GYD",
      countryCode: "GY",
      flag: "GY",
    },
    {
      value: "HT",
      label: "Haiti",
      phoneCode: "+509",
      currencyCode: "HTG",
      countryCode: "HT",
      flag: "HT",
    },
    {
      value: "HM",
      label: "Heard Island and McDonald Islands",
      phoneCode: "+61",
      currencyCode: "AUD",
      countryCode: "HM",
      flag: "HM",
    },
    {
      value: "VA",
      label: "Holy See",
      phoneCode: "+39",
      currencyCode: "EUR",
      countryCode: "VA",
      flag: "VA",
    },
    {
      value: "HN",
      label: "Honduras",
      phoneCode: "+504",
      currencyCode: "HNL",
      countryCode: "HN",
      flag: "HN",
    },
    {
      value: "HK",
      label: "Hong Kong",
      phoneCode: "+852",
      currencyCode: "HKD",
      countryCode: "HK",
      flag: "HK",
    },
    {
      value: "HU",
      label: "Hungary",
      phoneCode: "+36",
      currencyCode: "HUF",
      countryCode: "HU",
      flag: "HU",
    },
    {
      value: "IS",
      label: "Iceland",
      phoneCode: "+354",
      currencyCode: "ISK",
      countryCode: "IS",
      flag: "IS",
    },
    {
      value: "IN",
      label: "India",
      phoneCode: "+91",
      currencyCode: "INR",
      countryCode: "IN",
      flag: "IN",
    },
    {
      value: "ID",
      label: "Indonesia",
      phoneCode: "+62",
      currencyCode: "IDR",
      countryCode: "ID",
      flag: "ID",
    },
    {
      value: "IR",
      label: "Iran",
      phoneCode: "+98",
      currencyCode: "IRR",
      countryCode: "IR",
      flag: "IR",
    },
    {
      value: "IQ",
      label: "Iraq",
      phoneCode: "+964",
      currencyCode: "IQD",
      countryCode: "IQ",
      flag: "IQ",
    },
    {
      value: "IE",
      label: "Ireland",
      phoneCode: "+353",
      currencyCode: "EUR",
      countryCode: "IE",
      flag: "IE",
    },
    {
      value: "IM",
      label: "Isle of Man",
      phoneCode: "+44",
      currencyCode: "GBP",
      countryCode: "IM",
      flag: "IM",
    },
    {
      value: "IL",
      label: "Israel",
      phoneCode: "+972",
      currencyCode: "ILS",
      countryCode: "IL",
      flag: "IL",
    },
    {
      value: "IT",
      label: "Italy",
      phoneCode: "+39",
      currencyCode: "EUR",
      countryCode: "IT",
      flag: "IT",
    },
    {
      value: "JM",
      label: "Jamaica",
      phoneCode: "+1",
      currencyCode: "JMD",
      countryCode: "JM",
      flag: "JM",
    },
    {
      value: "JP",
      label: "Japan",
      phoneCode: "+81",
      currencyCode: "JPY",
      countryCode: "JP",
      flag: "JP",
    },
    {
      value: "JE",
      label: "Jersey",
      phoneCode: "+44",
      currencyCode: "GBP",
      countryCode: "JE",
      flag: "JE",
    },
    {
      value: "JO",
      label: "Jordan",
      phoneCode: "+962",
      currencyCode: "JOD",
      countryCode: "JO",
      flag: "JO",
    },
    {
      value: "KZ",
      label: "Kazakhstan",
      phoneCode: "+7",
      currencyCode: "KZT",
      countryCode: "KZ",
      flag: "KZ",
    },
    {
      value: "KE",
      label: "Kenya",
      phoneCode: "+254",
      currencyCode: "KES",
      countryCode: "KE",
      flag: "KE",
    },
    {
      value: "KI",
      label: "Kiribati",
      phoneCode: "+686",
      currencyCode: "AUD",
      countryCode: "KI",
      flag: "KI",
    },
    {
      value: "KP",
      label: "Korea, Democratic People's Republic of",
      phoneCode: "+850",
      currencyCode: "KPW",
      countryCode: "KP",
      flag: "KP",
    },
    {
      value: "KR",
      label: "Korea, Republic of",
      phoneCode: "+82",
      currencyCode: "KRW",
      countryCode: "KR",
      flag: "KR",
    },
    {
      value: "KW",
      label: "Kuwait",
      phoneCode: "+965",
      currencyCode: "KWD",
      countryCode: "KW",
      flag: "KW",
    },
    {
      value: "KG",
      label: "Kyrgyzstan",
      phoneCode: "+996",
      currencyCode: "KGS",
      countryCode: "KG",
      flag: "KG",
    },
    {
      value: "LA",
      label: "Lao People's Democratic Republic",
      phoneCode: "+856",
      currencyCode: "LAK",
      countryCode: "LA",
      flag: "LA",
    },
    {
      value: "LV",
      label: "Latvia",
      phoneCode: "+371",
      currencyCode: "EUR",
      countryCode: "LV",
      flag: "LV",
    },
    {
      value: "LB",
      label: "Lebanon",
      phoneCode: "+961",
      currencyCode: "LBP",
      countryCode: "LB",
      flag: "LB",
    },
    {
      value: "LS",
      label: "Lesotho",
      phoneCode: "+266",
      currencyCode: "LSL",
      countryCode: "LS",
      flag: "LS"
    },
    {
      value: "LR",
      label: "Liberia",
      phoneCode: "+231",
      currencyCode: "LRD",
      countryCode: "LR",
      flag: "LR",
    },
    {
      value: "LY",
      label: "Libya",
      phoneCode: "+218",
      currencyCode: "LYD",
      countryCode: "LY",
      flag: "LY",
    },
    {
      value: "LI",
      label: "Liechtenstein",
      phoneCode: "+423",
      currencyCode: "CHF",
      countryCode: "LI",
      flag: "LI",
    },
    {
      value: "LT",
      label: "Lithuania",
      phoneCode: "+370",
      currencyCode: "EUR",
      countryCode: "LT",
      flag: "LT",
    },
    {
      value: "LU",
      label: "Luxembourg",
      phoneCode: "+352",
      currencyCode: "EUR",
      countryCode: "LU",
      flag: "LU",
    },
    {
      value: "MO",
      label: "Macao",
      phoneCode: "+853",
      currencyCode: "MOP",
      countryCode: "MO",
      flag: "MO",
    },
    {
      value: "MG",
      label: "Madagascar",
      phoneCode: "+261",
      currencyCode: "MGA",
      countryCode: "MG",
      flag: "MG",
    },
    {
      value: "MW",
      label: "Malawi",
      phoneCode: "+265",
      currencyCode: "MWK",
      countryCode: "MW",
      flag: "MW",
    },
    {
      value: "MY",
      label: "Malaysia",
      phoneCode: "+60",
      currencyCode: "MYR",
      countryCode: "MY",
      flag: "MY",
    },
    {
      value: "MV",
      label: "Maldives",
      phoneCode: "+960",
      currencyCode: "MVR",
      countryCode: "MV",
      flag: "MV",
    },
    {
      value: "ML",
      label: "Mali",
      phoneCode: "+223",
      currencyCode: "XOF",
      countryCode: "ML",
      flag: "ML",
    },
    {
      value: "MT",
      label: "Malta",
      phoneCode: "+356",
      currencyCode: "EUR",
      countryCode: "MT",
      flag: "MT",
    },
    {
      value: "MH",
      label: "Marshall Islands",
      phoneCode: "+692",
      currencyCode: "USD",
      countryCode: "MH",
      flag: "MH",
    },
    {
      value: "MQ",
      label: "Martinique",
      phoneCode: "+596",
      currencyCode: "EUR",
      countryCode: "MQ",
      flag: "MQ",
    },
    {
      value: "MR",
      label: "Mauritania",
      phoneCode: "+222",
      currencyCode: "MRU",
      countryCode: "MR",
      flag: "MR",
    },
    {
      value: "MU",
      label: "Mauritius",
      phoneCode: "+230",
      currencyCode: "MUR",
      countryCode: "MU",
      flag: "MU",
    },
    {
      value: "YT",
      label: "Mayotte",
      phoneCode: "+262",
      currencyCode: "EUR",
      countryCode: "YT",
      flag: "YT",
    },
    {
      value: "MX",
      label: "Mexico",
      phoneCode: "+52",
      currencyCode: "MXN",
      countryCode: "MX",
      flag: "MX",
    },
    {
      value: "FM",
      label: "Micronesia",
      phoneCode: "+691",
      currencyCode: "USD",
      countryCode: "FM",
      flag: "FM",
    },
    {
      value: "MD",
      label: "Moldova",
      phoneCode: "+373",
      currencyCode: "MDL",
      countryCode: "MD",
      flag: "MD",
    },
    {
      value: "MC",
      label: "Monaco",
      phoneCode: "+377",
      currencyCode: "EUR",
      countryCode: "MC",
      flag: "MC",
    },
    {
      value: "MN",
      label: "Mongolia",
      phoneCode: "+976",
      currencyCode: "MNT",
      countryCode: "MN",
      flag: "MN",
    },
    {
      value: "ME",
      label: "Montenegro",
      phoneCode: "+382",
      currencyCode: "EUR",
      countryCode: "ME",
   
      flag: "ME",
    },
    {
      value: "MS",
      label: "Montserrat",
      phoneCode: "+1664",
      currencyCode: "XCD",
      countryCode: "MS",
      flag: "MS",
    },
    {
      value: "MA",
      label: "Morocco",
      phoneCode: "+212",
      currencyCode: "MAD",
      countryCode: "MA",
      flag: "MA",
    },
    {
      value: "MZ",
      label: "Mozambique",
      phoneCode: "+258",
      currencyCode: "MZN",
      countryCode: "MZ",
      flag: "MZ",
    },
    {
      value: "MM",
      label: "Myanmar",
      phoneCode: "+95",
      currencyCode: "MMK",
      countryCode: "MM",
      flag: "MM",
    },
    {
      value: "NA",
      label: "Namibia",
      phoneCode: "+264",
      currencyCode: "NAD",
      countryCode: "NA",
      flag: "NA",
    },
    {
      value: "NR",
      label: "Nauru",
      phoneCode: "+674",
      currencyCode: "AUD",
      countryCode: "NR",
      flag: "NR",
    },
    {
      value: "NP",
      label: "Nepal",
      phoneCode: "+977",
      currencyCode: "NPR",
      countryCode: "NP",
      flag: "NP",
    },
    {
      value: "NL",
      label: "Netherlands",
      phoneCode: "+31",
      currencyCode: "EUR",
      countryCode: "NL",
      flag: "NL",
    },
    {
      value: "NC",
      label: "New Caledonia",
      phoneCode: "+687",
      currencyCode: "XPF",
      countryCode: "NC",
      flag: "NC",
    },
    {
      value: "NZ",
      label: "New Zealand",
      phoneCode: "+64",
      currencyCode: "NZD",
      countryCode: "NZ",
      flag: "NZ",
    },
    {
      value: "NI",
      label: "Nicaragua",
      phoneCode: "+505",
      currencyCode: "NIO",
      countryCode: "NI",
      flag: "NI",
    },
    {
      value: "NE",
      label: "Niger",
      phoneCode: "+227",
      currencyCode: "XOF",
      countryCode: "NE",
      flag: "NE",
    },
    {
      value: "NG",
      label: "Nigeria",
      phoneCode: "+234",
      currencyCode: "NGN",
      countryCode: "NG",
      flag: "NG",
    },
    {
      value: "NU",
      label: "Niue",
      phoneCode: "+683",
      currencyCode: "NZD",
      countryCode: "NU",
      flag: "NU",
    },
    {
      value: "NF",
      label: "Norfolk Island",
      phoneCode: "+672",
      currencyCode: "AUD",
      countryCode: "NF",
      flag: "NF",
    },
    {
      value: "MP",
      label: "Northern Mariana Islands",
      phoneCode: "+1670",
      currencyCode: "USD",
      countryCode: "MP",
      flag: "MP",
    },
    {
      value: "NO",
      label: "Norway",
      phoneCode: "+47",
      currencyCode: "NOK",
      countryCode: "NO",
      flag: "NO",
    },
    {
      value: "OM",
      label: "Oman",
      phoneCode: "+968",
      currencyCode: "OMR",
      countryCode: "OM",
      flag: "OM",
    },
    {
      value: "PK",
      label: "Pakistan",
      phoneCode: "+92",
      currencyCode: "PKR",
      countryCode: "PK",
      flag: "PK",
    },
    {
      value: "PW",
      label: "Palau",
      phoneCode: "+680",
      currencyCode: "USD",
      countryCode: "PW",
      flag: "PW",
    },
    {
      value: "PS",
      label: "Palestine, State of",
      phoneCode: "+970",
      currencyCode: "ILS",
      countryCode: "PS",
      flag: "PS",
    },
    {
      value: "PA",
      label: "Panama",
      phoneCode: "+507",
      currencyCode: "PAB",
      countryCode: "PA",
      flag: "PA",
    },
    {
      value: "PG",
      label: "Papua New Guinea",
      phoneCode : "+675",
      currencyCode: "PGK",
      countryCode: "PG",
      flag: "PG",
    },
    {
      value: "PY",
      label: "Paraguay",
      phoneCode: "+595",
      currencyCode: "PYG",
      countryCode: "PY",
      flag: "PY",
    },
    {
      value: "PE",
      label: "Peru",
      phoneCode: "+51",
      currencyCode: "PEN",
      countryCode: "PE",
      flag: "PE",
    },
    {
      value: "PH",
      label: "Philippines",
      phoneCode: "+63",
      currencyCode: "PHP",
      countryCode: "PH",
      flag: "PH",
    },
    {
      value: "PN",
      label: "Pitcairn",
      phoneCode: "+64",
      currencyCode: "NZD",
      countryCode: "PN",
      flag: "PN",
    },
    {
      value: "PL",
      label: "Poland",
      phoneCode: "+48",
      currencyCode: "PLN",
      countryCode: "PL",
      flag: "PL",
    },
    {
      value: "PT",
      label: "Portugal",
      phoneCode: "+351",
      currencyCode: "EUR",
      countryCode: "PT",
      flag: "PT",
    },
    {
      value: "PR",
      label: "Puerto Rico",
      phoneCode: "+1",
      currencyCode: "USD",
      countryCode: "PR",
      flag: "PR",
    },
    {
      value: "QA",
      label: "Qatar",
      phoneCode: "+974",
      currencyCode: "QAR",
      countryCode: "QA",
      flag: "QA",
    },
    {
      value: "RE",
      label: "Réunion",
      phoneCode: "+262",
      currencyCode: "EUR",
      countryCode: "RE",
      flag: "RE",
    },
    {
      value: "RO",
      label: "Romania",
      phoneCode: "+40",
      currencyCode: "RON",
      countryCode: "RO",
      flag: "RO",
    },
    {
      value: "RU",
      label: "Russian Federation",
      phoneCode: "+7",
      currencyCode: "RUB",
      countryCode: "RU",
      flag: "RU",
    },
    {
      value: "RW",
      label: "Rwanda",
      phoneCode: "+250",
      currencyCode: "RWF",
      countryCode: "RW",
      flag: "RW",
    },
    {
      value: "BL",
      label: "Saint Bartelemy",
      phoneCode: "+590",
      currencyCode: "EUR",
      countryCode: "BL",
      flag: "BL",
    },
    {
      value: "SH",
      label: "Saint Helena",
      phoneCode: "+290",
      currencyCode: "SHP",
      countryCode: "SH",
      flag: "SH",
    },
    {
      value: "KN",
      label: "Saint Kitts and Nevis",
      phoneCode: "+1869",
      currencyCode: "XCD",
      countryCode: "KN",
      flag: "KN",
    },
    {
      value: "LC",
      label: "Saint Lucia",
      phoneCode: "+1758",
      currencyCode: "XCD",
      countryCode: "LC",
      flag: "LC",
    },
    {
      value: "MF",
      label: "Saint Martin (French part)",
      phoneCode: "+590",
      currencyCode: "EUR",
      countryCode: "MF",
      flag: "MF",
    },
    {
      value: "PM",
      label: "Saint Pierre and Miquelon",
      phoneCode: "+508",
      currencyCode: "EUR",
      countryCode: "PM",
      flag: "PM",
    },
    {
      value: "VC",
      label: "Saint Vincent and the Grenadines",
      phoneCode: "+1784",
      currencyCode: "XCD",
      countryCode: "VC",
      flag: "VC",
    },
    {
      value: "WS",
      label: "Samoa",
      phoneCode: "+685",
      currencyCode: "WST",
      countryCode: "WS",
      flag: "WS",
    },
    {
      value: "SM",
      label: "San Marino",
      phoneCode: "+378",
      currencyCode: "EUR",
      countryCode: "SM",
      flag: "SM",
    },
    {
      value: "ST",
      label: "Sao Tome and Principe",
      phoneCode: "+239",
      currencyCode: "STN",
   countryCode: "ST",
      flag: "ST",
    },
    {
      value: "SA",
      label: "Saudi Arabia",
      phoneCode: "+966",
      currencyCode: "SAR",
      countryCode: "SA",
      flag: "SA",
    },
    {
      value: "SN",
      label: "Senegal",
      phoneCode: "+221",
      currencyCode: "XOF",
      countryCode: "SN",
      flag: "SN",
    },
    {
      value: "RS",
      label: "Serbia",
      phoneCode: "+381",
      currencyCode: "RSD",
      countryCode: "RS",
      flag: "RS",
    },
    {
      value: "SC",
      label: "Seychelles",
      phoneCode: "+248",
      currencyCode: "SCR",
      countryCode: "SC",
      flag: "SC",
    },
    {
      value: "SL",
      label: "Sierra Leone",
      phoneCode: "+232",
      currencyCode: "SLL",
      countryCode: "SL",
      flag: "SL",
    },
    {
      value: "SG",
      label: "Singapore",
      phoneCode: "+65",
      currencyCode: "SGD",
      countryCode: "SG",
      flag: "SG",
    },
    {
      value: "SX",
      label: "Sint Maarten (Dutch part)",
      phoneCode: "+1721",
      currencyCode: "ANG",
      countryCode: "SX",
      flag: "SX",
    },
    {
      value: "SK",
      label: "Slovakia",
      phoneCode: "+421",
      currencyCode: "EUR",
      countryCode: "SK",
      flag: "SK",
    },
    {
      value: "SI",
      label: "Slovenia",
      phoneCode: "+386",
      currencyCode: "EUR",
      countryCode: "SI",
      flag: "SI",
    },
    {
      value: "SB",
      label: "Solomon Islands",
      phoneCode: "+677",
      currencyCode: "AUD",
      countryCode: "SB",
      flag: "SB",
    },
    {
      value: "SO",
      label: "Somalia",
      phoneCode: "+252",
      currencyCode: "SOS",
      countryCode: "SO",
      flag: "SO",
    },
    {
      value: "ZA",
      label: "South Africa",
      phoneCode: "+27",
      currencyCode: "ZAR",
      countryCode: "ZA",
      flag: "ZA",
    },
    {
      value: "GS",
      label: "South Georgia and the South Sandwich Islands",
      phoneCode: "+500",
      currencyCode: "GBP",
      countryCode: "GS",
      flag: "GS",
    },
    {
      value: "SS",
      label: "South Sudan",
      phoneCode: "+211",
      currencyCode: "SSP",
      countryCode: "SS",
      flag: "SS",
    },
    {
      value: "ES",
      label: "Spain",
      phoneCode: "+34",
      currencyCode: "EUR",
      countryCode: "ES",
      flag: "ES",
    },
    {
      value: "LK",
      label: "Sri Lanka",
      phoneCode: "+94",
      currencyCode: "LKR",
      countryCode: "LK",
      flag: "LK",
    },
    {
      value: "SD",
      label: "Sudan",
      phoneCode: "+249",
      currencyCode: "SDG",
      countryCode: "SD",
      flag: "SD",
    },
    {
      value: "SR",
      label: "Suriname",
      phoneCode: "+597",
      currencyCode: "SRD",
      countryCode: "SR",
      flag: "SR",
    },
    {
      value: "SJ",
      label: "Svalbard and Jan Mayen",
      phoneCode: "+47",
      currencyCode: "NOK",
      countryCode: "SJ",
      flag: "SJ",
    },
    {
      value: "SZ",
      label: "Sweden",
      phoneCode: "+46",
      currencyCode: "SEK",
      countryCode: "SE",
      flag: "SE",
    },
    {
      value: "CH",
      label: "Switzerland",
      phoneCode: "+41",
      currencyCode: "CHF",
      countryCode: "CH",
      flag: "CH",
    },
    {
      value: "SY",
      label: "Syrian Arab Republic",
      phoneCode: "+963",
      currencyCode: "SYP",
      countryCode: "SY",
      flag: "SY",
    },
    {
      value: "TW",
      label: "Taiwan",
      phoneCode: "+886",
      currencyCode: "TWD",
      countryCode: "TW",
      flag: "TW",
    },
    {
      value: "TJ",
      label: "Tajikistan",
      phoneCode: "+992",
      currencyCode: "TJS",
      countryCode: "TJ",
      flag: "TJ",
    },
    {
      value: "TZ",
      label: "Tanzania, United Republic of",
      phoneCode: "+255",
      currencyCode: "TZS",
      countryCode: "TZ",
      flag: "TZ",
    },
    {
      value: "TH",
      label: "Thailand",
      phoneCode: "+66",
      currencyCode: "THB",
      countryCode: "TH",
      flag: "TH",
    },
    {
      value: "TL",
      label: "Timor-Leste",
      phoneCode: "+670",
      currencyCode: "USD",
      countryCode: "TL",
      flag: "TL",
    },
    {
      value: "TG",
      label: "Togo",
      phoneCode: "+228",
      currencyCode: "XOF",
      countryCode: "TG",
      flag: "TG",
    },
    {
      value: "TK",
      label: "Tokelau",
      phoneCode: "+690",
      currencyCode: "NZD",
      countryCode: "TK",
      flag: "TK",
    },
    {
      value: "TO",
      label: "Tonga",
      phoneCode: "+676",
      currencyCode: "TOP",
      countryCode: "TO",
      flag: "TO",
    },
    {
      value: "TT",
      label: "Trinidad and Tobago",
      phoneCode: "+1868",
      currencyCode: "TTD",
      countryCode: "TT",
      flag: "TT",
    },
    {
      value: "TN",
      label: "Tunisia",
      phoneCode: "+216",
      currencyCode: "TND",
      countryCode: "TN",
      flag: "TN",
    },
    {
      value: "TR",
      label: "Turkey",
      phoneCode: "+90",
      currencyCode: "TRY",
      countryCode: "TR",
      flag: "TR",
    },
    {
      value: "TM",
      label: "Turkmenistan",
      phoneCode: "+993",
      currencyCode: "TMT",
      countryCode: "TM",
      flag: "TM",
    },
    {
      value: "TC",
      label: "Turks and Caicos Islands",
      phoneCode: "+1649",
      currencyCode: "USD",
      countryCode: "TC",
      flag: "TC",
    },
    {
      value: "TV",
      label: "Tuvalu",
      phoneCode: "+688",
      currencyCode: "AUD",
      countryCode: "TV",
      flag: "TV",
    },
    {
      value: "UG",
      label: "Uganda",
      phoneCode: "+256",
      currencyCode: "UGX",
      countryCode: "UG",
      flag: "UG",
    },
    {
      value: "UA",
      label: "Ukraine",
      phoneCode: "+380",
      currencyCode: "UAH",
      countryCode: "UA",
      flag: "UA",
    },
    {
      value: "AE",
      label: "United Arab Emirates",
      phoneCode: "+971",
      currencyCode: "AED",
      countryCode: "AE",
      flag: "AE",
    },
    {
      value: "GB",
      label: "United Kingdom",
      phoneCode: "+44",
      currencyCode: "GBP",
      countryCode: "GB",
      flag: "GB",
    },
    {
      value: "US",
      label: "United States",
      phoneCode: "+1",
      currencyCode: "USD",
      countryCode: "US",
      flag: "US",
    },
    {
      value: "UY",
      label: "Uruguay",
      phoneCode: "+598",
      currencyCode: "UYU",
      countryCode: "UY",
      flag: "UY",
    },
    {
      value: "UZ",
      label: "Uzbekistan",
      phoneCode: "+998",
      currencyCode: "UZS",
      countryCode: "UZ",
      flag: "UZ",
    },
    {
      value: "VU",
      label: "Vanuatu",
      phoneCode: "+678",
      currencyCode: "VUV",
      countryCode: "VU",
      flag: "VU",
    },
    {
      value: "VE",
      label: "Venezuela",
      phoneCode: "+58",
      currencyCode: "VES",
      countryCode: "VE",
      flag: "VE",
    },
    {
      value: "VN",
      label: "Viet Nam",
      phoneCode: "+84",
      currencyCode: "VND",
      countryCode: "VN",
      flag: "VN",
    },
    {
      value: "WF",
      label: "Wallis and Futuna",
      phoneCode: "+681",
      currencyCode: "XPF",
      countryCode: "WF",
      flag: "WF",
    },
    {
      value: "EH",
      label: "Western Sahara",
      phoneCode: "+212",
      currencyCode: "MAD",
      countryCode: "EH",
      flag: "EH",
    },
    {
      value: "YE",
      label: "Yemen",
      phoneCode: "+967",
      currencyCode: "YER",
      countryCode: "YE",
      flag: "YE",
    },
    {
      value: "ZM",
      label: "Zambia",
      phoneCode: "+260",
      currencyCode: "ZMW",
      countryCode: "ZM",
      flag: "ZM",
    },
    {
      value: "ZW",
      label: "Zimbabwe",
      phoneCode: "+263",
      currencyCode: "ZWL",
      countryCode: "ZW",
      flag: "ZW",
    },
  ];
  
  export default countries;